name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    - name: Run Robot Framework Tests
      run: |
        mkdir -p reports  # Criar diretório para relatórios
        rfbrowser init
        pabot --processes 3 --testlevelsplit --variable BROWSER_MODE:true --outputdir reports features/
        if [ $? -ne 0 ]; then
          echo "Robot Framework tests failed. Check the logs for details."
          exit 1
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/

  generate_report:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download reports
      uses: actions/download-artifact@v3
      with:
        name: reports
        path: reports/

    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.5
      with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: reports/
          log_path: reports/
          output_path: reports/
