name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Defina a versão do Python conforme necessário

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pabot --processes 3 --testlevelsplit --outputdir results --variable BROWSER_MODE:true features/

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/

  generate_report:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: results
          path: results/

      - name: Check downloaded files
        run: |
          echo "Checking downloaded reports..."
          ls -la results  # Verificando os arquivos no diretório 'results'

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report: results/report.html
          log: results/log.html
          output: results/output.xml
