name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright and system dependencies
      run: |
        python -m playwright install
        sudo apt-get update
    
    - name: Run Robot Framework Tests
      run: |
        rfbrowser init
        pabot --processes 3 --testlevelsplit --variable BROWSER_MODE:true --outputdir reports features/
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-results
        path: |
          reports/
          *.html
          *.xml
          *.png

  generate_report:
    runs-on: ubuntu-latest
    needs: run-tests
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        name: reports
        path: reports/

    - name: Check downloaded files
      run: |
        echo "Checking downloaded reports..."
        ls -la reports

    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.5
      with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report: reports/report.html
          log: reports/log.html
          output: reports/output.xml
