name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install robotframework-browser robotframework-pabot pyyaml
        
    - name: Install Playwright and system dependencies
      run: |
        pip install playwright
        python -m playwright install
        # sudo apt-get update
        # sudo apt-get install -y xvfb

    - name: Run Robot Framework Tests
      run: |
        rfbrowser init
        pabot --processes 3 --testlevelsplit --outputdir results --variable BROWSER_MODE:true features/
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-results
        path: |
          results/
          *.html
          *.xml
          *.png
